// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTD4hVKygRLY8Nq5Z0IFpUXKRoemjk2I',
    appId: '1:876738271742:web:18daa4b11e53b7144d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    authDomain: 'testapp-4e95c.firebaseapp.com',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    measurementId: 'G-NE1M11SKBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsyezKEmZStWM5AXP1pNAHatA85UlWiM',
    appId: '1:876738271742:android:9e5a4d189adf404e4d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImrdoQkJjoF5GF-XJFdLt_gzzIfD77jQ',
    appId: '1:876738271742:ios:6775619b85a52fa24d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    iosBundleId: 'com.example.flutterB3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImrdoQkJjoF5GF-XJFdLt_gzzIfD77jQ',
    appId: '1:876738271742:ios:6775619b85a52fa24d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    iosBundleId: 'com.example.flutterB3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTD4hVKygRLY8Nq5Z0IFpUXKRoemjk2I',
    appId: '1:876738271742:web:3aadde3980ba6db74d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    authDomain: 'testapp-4e95c.firebaseapp.com',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    measurementId: 'G-V25W3CR5VX',
  );
}
